### ISSUE TITLE
MASE for conditional age-at-length data

### ISSUE THREAD

**Issue by MOshima-PIFSC** [PIFSCstockassessments/ss3diags#32]
Add conditional age-at-length as an option for MASE calculation

**Comment by MOshima-PIFSC** [comment]
Changes included in commit:
- added "con" in SSretroComps to pull conditional age-at-length data and calculate residuals using SScompsTA1.8()
- added likelihood column into runs_dat for SScompsTA1.8 output 
- added "con" as a quants option in SSmase

**Comment by efletcherPIFSC** [comment]
@MOshima-PIFSC 
References to commit 28048b1a0685e304ceb14b1c703291e309e60fe0 and db6e8879069280cf8955d9a59bbbbb4bcee63c1e?
