### ISSUE TITLE
Fixup links to Cookbook scripts.

### ISSUE THREAD

**Issue by efletcherPIFSC** [PIFSCstockassessments/ss3diags#49]
## Issue 
In the ss3diags README, there are 4 relative inks to the cookbook scripts. They point to the R scripts in the Cookbook subdirectory,. However, the pkgdown site has a different directory structure. The cookbook script links in the ss3diags pkgdown site README (https://pifscstockassessments.github.io/ss3diags/) are invalid.

### Resolution
Replace README's cookbook relative links to code file links from the master branch

**Comment by MOshima-PIFSC** [comment]
In 'Retrospective and Forecast Bias' section, the last sentence in the first paragraph should be fixed from:
"An example of a retrospective analysis can be loaded in for use and summarized by"
to:
"An example of a retrospective analysis can be loaded in for use and summarized by
```r
data("retroSimple")
sumSimple <- r4ss::SSsummarize(retroSimple)
```
